// Sample data for the Ulox platform

export const properties = [
  {
    id: '1',
    title: 'Modern Downtown Apartment',
    price: 2500,
    currency: 'USD',
    type: 'rent' as const,
    location: 'Downtown District, NYC',
    beds: 2,
    baths: 2,
    sqft: 1200,
    image: 'https://picsum.photos/seed/prop1/400/300',
    verified: true,
    featured: true,
    agent: {
      name: 'Sarah Johnson',
      company: 'Prime Realty',
      image: 'https://picsum.photos/seed/agent1/100/100',
    },
    amenities: ['Parking', 'Gym', 'Pool', 'Pet Friendly'],
    description: 'Beautiful modern apartment with stunning city views.',
  },
  {
    id: '2',
    title: 'Cozy Studio Loft',
    price: 1800,
    currency: 'USD',
    type: 'rent' as const,
    location: 'Arts District, LA',
    beds: 1,
    baths: 1,
    sqft: 800,
    image: 'https://picsum.photos/seed/prop2/400/300',
    verified: true,
    featured: false,
    agent: {
      name: 'Mike Chen',
      company: 'Urban Living',
      image: 'https://picsum.photos/seed/agent2/100/100',
    },
    amenities: ['Parking', 'Laundry'],
    description: 'Perfect for young professionals in the heart of the arts district.',
  },
  {
    id: '3',
    title: 'Family Home with Garden',
    price: 450000,
    currency: 'USD',
    type: 'buy' as const,
    location: 'Suburban Heights, TX',
    beds: 4,
    baths: 3,
    sqft: 2500,
    image: 'https://picsum.photos/seed/prop3/400/300',
    verified: true,
    featured: true,
    agent: {
      name: 'Lisa Park',
      company: 'Family Homes Co',
      image: 'https://picsum.photos/seed/agent3/100/100',
    },
    amenities: ['Garage', 'Garden', 'Fireplace', 'School District'],
    description: 'Spacious family home in excellent school district.',
  },
  {
    id: '4',
    title: 'Luxury Penthouse',
    price: 8500,
    currency: 'USD',
    type: 'rent' as const,
    location: 'Upper East Side, NYC',
    beds: 3,
    baths: 3,
    sqft: 2200,
    image: 'https://picsum.photos/seed/prop4/400/300',
    verified: true,
    featured: true,
    agent: {
      name: 'David Rodriguez',
      company: 'Luxury Living',
      image: 'https://picsum.photos/seed/agent4/100/100',
    },
    amenities: ['Concierge', 'Rooftop', 'Valet', 'Gym'],
    description: 'Ultra-luxurious penthouse with panoramic city views.',
  },
];

export const roommates = [
  {
    id: '1',
    name: 'Emma Wilson',
    age: 25,
    budget: 1200,
    location: 'Downtown, NYC',
    image: 'https://picsum.photos/seed/roommate1/150/150',
    bio: 'Marketing professional, clean and organized. Love cooking and yoga.',
    lifestyle: ['Non-smoker', 'Pet-friendly', 'Quiet', 'Social'],
    compatibility: 95,
  },
  {
    id: '2',
    name: 'Alex Thompson',
    age: 28,
    budget: 1500,
    location: 'Brooklyn, NYC',
    image: 'https://picsum.photos/seed/roommate2/150/150',
    bio: 'Software engineer working remotely. Weekend hiker, loves tech.',
    lifestyle: ['Non-smoker', 'No pets', 'Early riser', 'Fitness'],
    compatibility: 87,
  },
  {
    id: '3',
    name: 'Maya Patel',
    age: 24,
    budget: 1000,
    location: 'Queens, NYC',
    image: 'https://picsum.photos/seed/roommate3/150/150',
    bio: 'Graduate student studying architecture. Creative and friendly.',
    lifestyle: ['Occasional smoker', 'Cat owner', 'Night owl', 'Artistic'],
    compatibility: 78,
  },
];

export const products = [
  {
    id: '1',
    name: 'Modern Coffee Table',
    price: 299,
    currency: 'USD',
    image: 'https://picsum.photos/seed/product1/300/300',
    rating: 4.8,
    reviews: 124,
    category: 'Furniture',
    inStock: true,
    description: 'Sleek modern coffee table perfect for any living room.',
  },
  {
    id: '2',
    name: 'Smart Home Security System',
    price: 199,
    currency: 'USD',
    image: 'https://picsum.photos/seed/product2/300/300',
    rating: 4.6,
    reviews: 89,
    category: 'Security',
    inStock: true,
    description: 'Complete home security system with mobile app control.',
  },
  {
    id: '3',
    name: 'LED Ceiling Light',
    price: 89,
    currency: 'USD',
    image: 'https://picsum.photos/seed/product3/300/300',
    rating: 4.4,
    reviews: 67,
    category: 'Lighting',
    inStock: true,
    description: 'Energy-efficient LED ceiling light with dimmer.',
  },
  {
    id: '4',
    name: 'Kitchen Appliance Set',
    price: 899,
    currency: 'USD',
    image: 'https://picsum.photos/seed/product4/300/300',
    rating: 4.9,
    reviews: 203,
    category: 'Appliances',
    inStock: false,
    description: 'Complete kitchen appliance set for modern homes.',
  },
];

export const services = [
  {
    id: '1',
    provider: 'CleanPro Services',
    service: 'House Cleaning',
    image: 'https://picsum.photos/seed/service1/200/200',
    rating: 4.9,
    reviews: 156,
    priceFrom: 80,
    category: 'Cleaning',
    description: 'Professional house cleaning with eco-friendly products.',
    availability: 'Available Today',
  },
  {
    id: '2',
    provider: 'FixIt Plumbing',
    service: 'Plumbing Repair',
    image: 'https://picsum.photos/seed/service2/200/200',
    rating: 4.7,
    reviews: 98,
    priceFrom: 120,
    category: 'Plumbing',
    description: '24/7 emergency plumbing services and repairs.',
    availability: 'Emergency Service',
  },
  {
    id: '3',
    provider: 'PowerUp Electric',
    service: 'Electrical Work',
    image: 'https://picsum.photos/seed/service3/200/200',
    rating: 4.8,
    reviews: 134,
    priceFrom: 100,
    category: 'Electrical',
    description: 'Licensed electricians for all your electrical needs.',
    availability: 'Next Day',
  },
];

export const jobs = [
  {
    id: '1',
    title: 'Construction Laborer',
    employer: 'BuildCorp Inc.',
    location: 'Manhattan, NYC',
    payRate: 25,
    payPeriod: 'hour',
    duration: '3 months',
    funded: true,
    status: 'open' as const,
    skills: ['Construction', 'Physical Labor', 'Safety'],
    description: 'Join our construction team for a major downtown project.',
    posted: '2 days ago',
  },
  {
    id: '2',
    title: 'Electrician Helper',
    employer: 'Spark Electric Co.',
    location: 'Brooklyn, NYC',
    payRate: 22,
    payPeriod: 'hour',
    duration: '6 weeks',
    funded: true,
    status: 'open' as const,
    skills: ['Electrical', 'Helper', 'Tools'],
    description: 'Assist licensed electricians with residential projects.',
    posted: '1 day ago',
  },
  {
    id: '3',
    title: 'Warehouse Worker',
    employer: 'LogiMove LLC',
    location: 'Queens, NYC',
    payRate: 18,
    payPeriod: 'hour',
    duration: '1 month',
    funded: true,
    status: 'open' as const,
    skills: ['Warehouse', 'Forklift', 'Inventory'],
    description: 'Temporary warehouse position for busy season.',
    posted: '3 days ago',
  },
];

export const reels = [
  {
    id: '1',
    title: 'Amazing Downtown Loft Tour',
    creator: 'PropertyTours',
    thumbnail: 'https://picsum.photos/seed/reel1/300/400',
    likes: 1234,
    comments: 89,
    shares: 45,
    propertyId: '1',
    duration: 45,
  },
  {
    id: '2',
    title: 'Home Staging Tips',
    creator: 'StageItRight',
    thumbnail: 'https://picsum.photos/seed/reel2/300/400',
    likes: 987,
    comments: 156,
    shares: 78,
    propertyId: null,
    duration: 32,
  },
  {
    id: '3',
    title: 'Kitchen Renovation Before/After',
    creator: 'RenovationPro',
    thumbnail: 'https://picsum.photos/seed/reel3/300/400',
    likes: 2156,
    comments: 234,
    shares: 123,
    propertyId: null,
    duration: 28,
  },
];

export const user = {
  id: '1',
  name: 'John Smith',
  email: 'john@example.com',
  phone: '+1 (555) 123-4567',
  avatar: 'https://picsum.photos/seed/user1/150/150',
  verified: true,
  kycStatus: 'approved',
  role: 'tenant',
  joinDate: '2024-01-15',
  stats: {
    savedListings: 12,
    purchases: 3,
    reviews: 8,
  },
};

export const notifications = [
  {
    id: '1',
    type: 'listing',
    title: 'New listing matches your search',
    message: 'Check out this 2-bed apartment in Downtown',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: '2',
    type: 'booking',
    title: 'Service booking confirmed',
    message: 'Your cleaning service is scheduled for tomorrow',
    timestamp: '1 day ago',
    read: true,
  },
];

export const disputes = [
  {
    id: '1',
    type: 'service',
    parties: ['John Smith', 'CleanPro Services'],
    status: 'pending',
    created: '2024-12-15',
    description: 'Service not completed as agreed',
    amount: 150,
  },
  {
    id: '2',
    type: 'rental',
    parties: ['Emma Wilson', 'Downtown Properties'],
    status: 'resolved',
    created: '2024-12-10',
    description: 'Security deposit dispute',
    amount: 1000,
  },
];

export const transactions = [
  {
    id: '1',
    type: 'rental_payment',
    amount: 2500,
    status: 'completed',
    date: '2024-12-15',
    description: 'Monthly rent payment',
    parties: ['John Smith', 'Downtown Properties'],
  },
  {
    id: '2',
    type: 'service_payment',
    amount: 150,
    status: 'pending',
    date: '2024-12-14',
    description: 'House cleaning service',
    parties: ['John Smith', 'CleanPro Services'],
  },
  {
    id: '3',
    type: 'product_purchase',
    amount: 299,
    status: 'completed',
    date: '2024-12-13',
    description: 'Modern Coffee Table',
    parties: ['John Smith', 'Ulox Store'],
  },
];